name: Publish Gallery
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  test:
    name: Publish Gallery to Github Pages
    if: ${{ github.repository != 'gautamkrishnar/github-pages-gallery' && github.event.head_commit.message != '' && github.event.head_commit.message != 'Initial commit' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Build Gallery 🔧
        run: docker run -v "$(pwd):/work" thumbsupgallery/thumbsup /bin/sh -c "cd /work/ && thumbsup --config config.json"
      - name: Package and upload artifact 📦
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: 'build_output'
          name: gh-pages
      - name: Deploy to Github Pages 🚀
        uses: actions/deploy-pages@v1
        with:
          artifact_name: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete artifact 🗑️
        uses: geekyeggo/delete-artifact@v2
        with:
          name: gh-pages
